[versions]
agp = "8.13.0"
kotlin = "2.0.21"
coreKtx = "1.17.0"
junit = "4.13.2"
junitVersion = "1.1.5"
espressoCore = "3.5.1"
lifecycleRuntimeKtx = "2.9.4"
activityCompose = "1.11.0"

androidGradlePlugin = "8.9.0"
androidxComposeMaterialIconsCore = "1.7.7"
androidxTestCore = "1.6.0"
androidxTestRules = "1.7.0"
androidxTestRunner = "1.6.0"
androidxComposeBom = "2025.03.00"
firebaseBom = "33.12.0"
guava = "33.4.5-android"
clarity = "3.1.2"
photoView = "2.2.0"

[libraries]
androidx-core-ktx = { group = "androidx.core", name = "core-ktx", version.ref = "coreKtx" }
junit = { group = "junit", name = "junit", version.ref = "junit" }
androidx-junit = { group = "androidx.test.ext", name = "junit", version.ref = "junitVersion" }
androidx-espresso-core = { group = "androidx.test.espresso", name = "espresso-core", version.ref = "espressoCore" }
androidx-lifecycle-runtime-ktx = { group = "androidx.lifecycle", name = "lifecycle-runtime-ktx", version.ref = "lifecycleRuntimeKtx" }
androidx-activity-compose = { group = "androidx.activity", name = "activity-compose", version.ref = "activityCompose" }
androidx-compose-ui = { group = "androidx.compose.ui", name = "ui" }
androidx-compose-ui-graphics = { group = "androidx.compose.ui", name = "ui-graphics" }
androidx-compose-ui-tooling = { group = "androidx.compose.ui", name = "ui-tooling" }
androidx-compose-ui-tooling-preview = { group = "androidx.compose.ui", name = "ui-tooling-preview" }
androidx-compose-ui-test-manifest = { group = "androidx.compose.ui", name = "ui-test-manifest" }
androidx-compose-ui-test-junit4 = { group = "androidx.compose.ui", name = "ui-test-junit4" }
androidx-compose-material3 = { group = "androidx.compose.material3", name = "material3" }

android-gradlePlugin = { group = "com.android.tools.build", name = "gradle", version.ref = "androidGradlePlugin" }
androidx-test-core = {group = "androidx.test", name = "core", version.ref = "androidxTestCore"}
androidx-text-core-ktx = {group = "androidx.test", name = "core-ktx", version.ref = "androidxTestCore"}
androidx-test-rules = {group = "androidx.test", name = "rules", version.ref = "androidxTestRules"}
androidx-test-runner = {group = "androidx.test", name = "runner", version.ref = "androidxTestRunner"}
androidx-compose-bom = { group = "androidx.compose", name = "compose-bom", version.ref = "androidxComposeBom" }
firebase-bom = { group = "com.google.firebase", name = "firebase-bom", version.ref = "firebaseBom" }
guava = { module = "com.google.guava:guava", version.ref = "guava" }
clarity = { group = "com.microsoft.clarity", name = "clarity", version.ref = "clarity" }
photoView = { group = "com.github.chrisbanes", name = "photoView", version.ref = "photoView" }

[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
kotlin-compose = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }
